# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rename.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 309)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 20, 361, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 70, 91, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox__3 = QtWidgets.QComboBox(Form)
        self.comboBox__3.setGeometry(QtCore.QRect(230, 70, 121, 22))
        self.comboBox__3.setObjectName("comboBox__3")
        self.comboBox__3.addItem("")
        self.comboBox__3.addItem("")
        self.comboBox__3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(360, 70, 81, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_1 = QtWidgets.QComboBox(Form)
        self.comboBox_1.setGeometry(QtCore.QRect(30, 70, 91, 22))
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_ = QtWidgets.QComboBox(Form)
        self.comboBox_.setGeometry(QtCore.QRect(450, 70, 81, 22))
        self.comboBox_.setObjectName("comboBox_")
        self.comboBox_.addItem("")
        self.comboBox_.addItem("")
        self.comboBox_.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(190, 260, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 260, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(30, 110, 491, 141))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dateTime = QtWidgets.QWidget()
        self.dateTime.setObjectName("dateTime")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.dateTime)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 0, 491, 141))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.dateTime_2 = QtWidgets.QWidget()
        self.dateTime_2.setObjectName("dateTime_2")
        self.label_datetime = QtWidgets.QLabel(self.dateTime_2)
        self.label_datetime.setGeometry(QtCore.QRect(220, 70, 54, 12))
        self.label_datetime.setObjectName("label_datetime")
        self.stackedWidget_2.addWidget(self.dateTime_2)
        self.sequence_2 = QtWidgets.QWidget()
        self.sequence_2.setObjectName("sequence_2")
        self.label_sequence_2 = QtWidgets.QLabel(self.sequence_2)
        self.label_sequence_2.setGeometry(QtCore.QRect(210, 80, 54, 12))
        self.label_sequence_2.setObjectName("label_sequence_2")
        self.stackedWidget_2.addWidget(self.sequence_2)
        self.date_2 = QtWidgets.QWidget()
        self.date_2.setObjectName("date_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.date_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 491, 131))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 40, 89, 16))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 60, 89, 16))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_9.setGeometry(QtCore.QRect(10, 80, 89, 16))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 100, 89, 16))
        self.radioButton_10.setObjectName("radioButton_10")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_7.setGeometry(QtCore.QRect(150, 60, 81, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(120, 60, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(250, 60, 21, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 30, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(280, 10, 54, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(280, 60, 81, 20))
        self.label_9.setObjectName("label_9")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(280, 80, 111, 19))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.stackedWidget_2.addWidget(self.date_2)
        self.stackedWidget.addWidget(self.dateTime)
        self.sequence = QtWidgets.QWidget()
        self.sequence.setObjectName("sequence")
        self.label_sequence = QtWidgets.QLabel(self.sequence)
        self.label_sequence.setGeometry(QtCore.QRect(210, 80, 54, 12))
        self.label_sequence.setObjectName("label_sequence")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.sequence)
        self.stackedWidget_3.setGeometry(QtCore.QRect(0, 0, 491, 141))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.dateTime_3 = QtWidgets.QWidget()
        self.dateTime_3.setObjectName("dateTime_3")
        self.label_datetime_2 = QtWidgets.QLabel(self.dateTime_3)
        self.label_datetime_2.setGeometry(QtCore.QRect(220, 70, 54, 12))
        self.label_datetime_2.setObjectName("label_datetime_2")
        self.stackedWidget_3.addWidget(self.dateTime_3)
        self.sequence_3 = QtWidgets.QWidget()
        self.sequence_3.setObjectName("sequence_3")
        self.label_sequence_3 = QtWidgets.QLabel(self.sequence_3)
        self.label_sequence_3.setGeometry(QtCore.QRect(210, 80, 54, 12))
        self.label_sequence_3.setObjectName("label_sequence_3")
        self.stackedWidget_3.addWidget(self.sequence_3)
        self.date_3 = QtWidgets.QWidget()
        self.date_3.setObjectName("date_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.date_3)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 491, 131))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 40, 89, 16))
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_13.setGeometry(QtCore.QRect(10, 60, 89, 16))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 80, 89, 16))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 100, 89, 16))
        self.radioButton_15.setObjectName("radioButton_15")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_8.setGeometry(QtCore.QRect(150, 60, 81, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(120, 60, 21, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(250, 60, 21, 16))
        self.label_11.setObjectName("label_11")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_16.setGeometry(QtCore.QRect(300, 40, 89, 16))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_17.setGeometry(QtCore.QRect(300, 60, 89, 16))
        self.radioButton_17.setObjectName("radioButton_17")
        self.stackedWidget_3.addWidget(self.date_3)
        self.stackedWidget.addWidget(self.sequence)
        self.date = QtWidgets.QWidget()
        self.date.setObjectName("date")
        self.groupBox = QtWidgets.QGroupBox(self.date)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 491, 131))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(230, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(230, 10, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(230, 60, 81, 20))
        self.label_5.setObjectName("label_5")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(230, 90, 111, 19))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.stackedWidget.addWidget(self.date)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(2)
        self.stackedWidget_3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "示例       <原名称>_2017.09.29_000.jpg"))
        self.comboBox_2.setItemText(0, _translate("Form", "下划线"))
        self.comboBox_2.setItemText(1, _translate("Form", "连字符"))
        self.comboBox_2.setItemText(2, _translate("Form", "空格"))
        self.comboBox_2.setItemText(3, _translate("Form", "无"))
        self.comboBox__3.setItemText(0, _translate("Form", "拍摄日期"))
        self.comboBox__3.setItemText(1, _translate("Form", "拍摄日期/时间"))
        self.comboBox__3.setItemText(2, _translate("Form", "序号"))
        self.comboBox_4.setItemText(0, _translate("Form", "下划线"))
        self.comboBox_4.setItemText(1, _translate("Form", "连字符"))
        self.comboBox_4.setItemText(2, _translate("Form", "空格"))
        self.comboBox_4.setItemText(3, _translate("Form", "无"))
        self.comboBox_1.setItemText(0, _translate("Form", "原名称"))
        self.comboBox_1.setItemText(1, _translate("Form", "新名称"))
        self.comboBox_1.setItemText(2, _translate("Form", "无"))
        self.comboBox_.setItemText(0, _translate("Form", "原名称"))
        self.comboBox_.setItemText(1, _translate("Form", "新名称"))
        self.comboBox_.setItemText(2, _translate("Form", "无"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.pushButton_2.setText(_translate("Form", "取消"))
        self.label_datetime.setText(_translate("Form", "B"))
        self.label_sequence_2.setText(_translate("Form", " C"))
        self.radioButton_6.setText(_translate("Form", "yyyymmdd"))
        self.radioButton_7.setText(_translate("Form", "yymmdd"))
        self.radioButton_8.setText(_translate("Form", "mmddyyyy"))
        self.radioButton_9.setText(_translate("Form", "mmddyy"))
        self.radioButton_10.setText(_translate("Form", "mmdd"))
        self.comboBox_7.setItemText(0, _translate("Form", "下划线"))
        self.comboBox_7.setItemText(1, _translate("Form", "连字符"))
        self.comboBox_7.setItemText(2, _translate("Form", "空格"))
        self.comboBox_7.setItemText(3, _translate("Form", "无"))
        self.label_6.setText(_translate("Form", "+"))
        self.label_7.setText(_translate("Form", "+"))
        self.label_8.setText(_translate("Form", "序号"))
        self.label_9.setText(_translate("Form", "序号码长度"))
        self.label_sequence.setText(_translate("Form", " C"))
        self.label_datetime_2.setText(_translate("Form", "B"))
        self.label_sequence_3.setText(_translate("Form", " C"))
        self.radioButton_11.setText(_translate("Form", "yyyymmdd"))
        self.radioButton_12.setText(_translate("Form", "yymmdd"))
        self.radioButton_13.setText(_translate("Form", "mmddyyyy"))
        self.radioButton_14.setText(_translate("Form", "mmddyy"))
        self.radioButton_15.setText(_translate("Form", "mmdd"))
        self.comboBox_8.setItemText(0, _translate("Form", "下划线"))
        self.comboBox_8.setItemText(1, _translate("Form", "连字符"))
        self.comboBox_8.setItemText(2, _translate("Form", "空格"))
        self.comboBox_8.setItemText(3, _translate("Form", "无"))
        self.label_10.setText(_translate("Form", "+"))
        self.label_11.setText(_translate("Form", "+"))
        self.radioButton_16.setText(_translate("Form", "hhmmss*"))
        self.radioButton_17.setText(_translate("Form", "hhmm*"))
        self.label_4.setText(_translate("Form", "序号"))
        self.label_5.setText(_translate("Form", "序号码长度"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

